language: android

sudo: true

env:
  global:
  - MALLOC_ARENA_MAX=2

android:
  components:
  - tools
  - platform-tools

  - build-tools-27.0.3
  - android-27

  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services

notifications:
  email: false

jdk:
- oraclejdk8

# workaround for https://github.com/travis-ci/travis-ci/issues/8874
before_install:
- yes | sdkmanager "platforms;android-27"

script:
- ./gradlew -PdisablePreDex assemble lint{With,No}GPlay{Debug,Release} test{With,No}GPlay{Debug,Release}UnitTest
